### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hallegu** [hallegu/Time-management-app#8]
Description of project purpose and goals. Basically, what will the app accomplish, what's our motivation, how will we achieve this, etc.

**Comment by kayverly** [comment]
We will be creating a time-management application that will help users prioritize assignments, set goals, and track what sites/apps they are spending the most time on. We plan on making different charts to help users track the time they are spending on different online activities. We will start the user's journey by entering their time goals and schedules. Then we can help users stay on track and on task. We also plan to give small notifications to praise or scold users based on their time management progress. Our goal is to help users plan their time efficiently so they get as much done as possible and can better succeed in life.
